import useStyles from "./styles";

const Abstruct = () => {
  const classes = useStyles();
  return (
    <div className={classes.mainContainer}>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
      <div>kjs</div>
    </div>
  );
};

export default Abstruct;
